version: '3.8'
# имена и описания контейнеров, которые должны быть развёрнуты
services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
       - .env
      # - ./.env 

  backend:
    image: vovanbart/foodgram_backend:latest
    # build: ../backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
      #- ./.env

  frontend:
    image: vovanbart/foodgram_frontend:latest
    # build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    # image: nginx:1.19.3
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
volumes:
  postgres_data:
  static_value:
  media_value: